language: generic
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - travis_wait docker build -t daverichmond/fpga-quartus .
  - docker push daverichmond/fpga-quartus
